#!/bin/sh

OSNAME=$(uname -o)
OSVERSION=$(uname -r)

echo "<HTML>"
echo "<HEAD>"
echo "  <TITLE>"
echo "  OSInfo"
echo "  </TITLE>"
echo "</HEAD>"
echo ""
echo "<BODY>"
echo "<H1>"
echo "System Information"
echo "</H1>"
echo "<P>"
echo "  OS: $OSNAME<br>"
echo "  Version: $OSVERSION"
echo "</P>"
echo "</BODY>"
echo "</HTML>"
